server {
  listen              443 ssl default_server;
  listen              [::]:443 ssl default_server ;
  server_name         nginx;

  ssl_certificate     /etc/nginx/certificate.cert;
  ssl_certificate_key /etc/nginx/private-key.key;
  
  proxy_set_header   Host $host;
  proxy_set_header   X-Forwarded-Proto https;

  location  /connector {
    rewrite /connector/(.*) /$1  break;
    proxy_pass         https://connector:8080;
    proxy_redirect     off;
  }

  location  /dashboard {
    client_max_body_size 0;
    rewrite /dashboard/(.*) /$1  break;
    proxy_pass         http://dashboard:3031;
    proxy_redirect     off;
  }
}

# Redirect Legacy HTTP Traffic
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;
  return 301 https://$host$request_uri;
}
